name: GitHub_Actions(shedule)
on:
  workflow_dispatch:
env:  #環境変数から文字列(パスワードなど)を取得
  ID: ${{secrets.ID}}
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6.15'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver  --upgrade
          pip install python-dotenv==0.19.2
          pip install selenium==3.141.0
          python schedule.py
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.0.7
